resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/16/20.yaml
packages:
  - .
extra-deps:
  - gloss-1.13.1.2
  - regex-posix-clib-2.7

flags:
  regex-posix:
    _regex-posix-clib: true
